version: '3'
services:
  db:
     image: mysql:5.7
     container_name: dustcloud-dbserver
     volumes:
       - db_data:/var/lib/mysql
       - ${PWD}/../dustcloud/dustcloud.sql:/docker-entrypoint-initdb.d/dustcloud.sql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: dustcloud
       MYSQL_DATABASE: dustcloud
       MYSQL_USER: dustcloud
       MYSQL_PASSWORD: dustcloud

  webserver:
    container_name: dustcloud-webserver
    build:
      context: ..
      dockerfile: ./docker/Dockerfile_webserver
    ports:
      - "2080:80"
    links:
      - db

  appserver:
    container_name: dustcloud-appserver
    build:
      context: ..
      dockerfile: ./docker/Dockerfile_appserver
    command: python3 /opt/dustcloud/server.py --enable-live-map --http-proxy webserver:80 -sport 1080
    ports:
      - "80:1080"
    links:
      - db
      - webserver

volumes:
    db_data: {}
  